#server:
#  port: 9001
#
#spring:
#  application:
#    name: xdclass-user-service
#  cloud:
#    #注册中心地址
#    nacos:
#      discovery:
#        server-addr: 39.104.131.130:8848
#
#  redis:
#    host: 39.104.131.130
#    password: 123456
#    port: 8000
#    timeout: 10000ms
#
#  #数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/xdclass_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: zzf19970112472X
#
#  mail:
#    host: smtp.163.com
#    username: zhangzhuofan2019@163.com #发送邮件的邮箱地址
#    password: OAYBPNUIDJAUTNEA #客户端授权码，不是邮箱密码,网易的是自己设置的
#    from: zhangzhuofan2019@163.com # 发送邮件的地址，和上面username一致
#    default-encoding: utf-8
#
##配置plus打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
##设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
#logging:
#  level:
#    root: INFO
#
#aliyun:
#  oss:
#    endpoint: oss-rg-china-mainland.aliyuncs.com
#    access-key-id: LTAI5tCJf3vzy3fTMYAgAt97
#    access-key-secret: uApqaGTBpzhpN514nBGwW8axY75P5F
#    bucketname: xdclass-zzf